// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iipirfpxxaeynucdebix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcGlyZnB4eGFleW51Y2RlYml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODEwNzUsImV4cCI6MjA1OTQ1NzA3NX0.CNbtRFmoEczXYlr4t59Rzy17sWI_Y7mtRzD2Ydy91Gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);